# Generated by Django 5.1.1 on 2024-09-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.CharField(max_length=100, verbose_name='User Email')),
                ('password', models.CharField(max_length=20, verbose_name='User Password')),
            ],
        ),
    ]
