# Generated by Django 5.1.1 on 2024-09-19 02:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('description', models.TextField(verbose_name='Post Description')),
                ('posted_date', models.DateField(default=datetime.date.today)),
                ('good_name', models.CharField(max_length=100, verbose_name='Good name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentbook.user')),
            ],
        ),
    ]
